[build]
  base = "."
  publish = "public"         # 仍然指向你存放静态文件的目录
  functions = "./.netlify/functions"    # 指定函数目录为 `functions` 文件夹



[[redirects]]
  from = "/"
  to = "/login.html"
  status = 200
  force = true  # 强制重定向


[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login"
  status = 200


# 删除不必要的重定向规则，因为你已经通过函数处理用户请求
[[redirects]]
  from = "/getUsers"
  to = "/.netlify/functions/getUsers"
  status = 200
  force = true


[[redirects]]
  from = "/deleteUser"
  to = "/.netlify/functions/deleteUser"
  status = 200




[[redirects]]
  from = "/api/receivingClient"  # 将前端的请求路由到此函数
  to = "/.netlify/functions/receivingClient"
  status = 200

[[redirects]]
  from = "/api/register"
  to = "/.netlify/functions/register"
  status = 200
